<?php

declare(strict_types=1);

namespace Test\FuluOpenApi;

use JavaReact\FuluOpenApi\Tools\AES;
use PHPUnit\Framework\TestCase;

/**
 * Class AESTest
 * @package Test\FuluOpenApi
 */
class AESTest extends TestCase
{


    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
    }

    /**
     * 测试解密
     */
    public function testAES()
    {
        $ori = AES::decode('Gu8k2+8wDXH3zpNv5MIFjZDTK0m1kvm99iBAKIWwQTo=', Contains::TEST_AES_SECRET);
        $this->assertSame('CD1000590202001040006363045', $ori);
    }
}